### PR TITLE
setup.py packaging

### PR DESCRIPTION
**Pull request by adamcharnock**
Hello,

I saw that 'setup.py packaging' was on the todo list so I thought I would see if I could help out. This pull request moves things around a bit, but it makes PyClojure installable via pip. It also makes the 'pyclojure' command available directly on the command line. You can currently test out the install by running:

```
pip install git+git://github.com/adamcharnock/PyClojure.git#egg=PyClojure
```

And then you should be able to do this:

```
$ pyclojure 
pylisp>
```

I put in sensible values in setup.py, but you will probably want to tweak them.

I used [seed](http://seed.readthedocs.org) to create the skeleton. You can also use seed for sending this package up to PyPi when you are ready too, which will also update the changelog and tag the release:

```
seed release --initial [--dry-run]
```

Full disclosure: I must confess to not having used Clojure very much at all, and I wrote the seed command as a little test project not long ago and this seemed like a prime chance to use it in the wild. None the less, I hope this is of some use!

### CODE REVIEW

**Comment by adamcharnock** [comment]
Hi John,

Ah yes, I forgot to add the shebang to the start of the setup.py file. The latest commit should sort that out.

Adam

**Comment by eigenhombre** [comment]
Got it -- I had to make a tweak to get it to work on my own setup -- does it still work on yours as merged?

**Comment by eigenhombre** [comment]
Closing this for now, but please reissue or open ticket if I missed something... many thanks!

**Comment by adamcharnock** [comment]
Nope, that all looks great! I did some digging around regarding setuptools/distutils and have submitted a minor pull request here:

https://github.com/eigenhombre/PyClojure/pull/5

No big deal really, just prevents people without setuptools or distribute from getting errors.

**Pull request closed without merging**
